// nav.ts generated by script,don't edit manually
export default [
  {
    text: 'Admin-App',
    link: '/Admin-App/index'
  },
  {
    text: 'AI',
    link: '/AI/index'
  },
  {
    text: 'Studio',
    link: '/Studio/index'
  },
  {
    text: 'YaoDSL',
    link: '/YaoDSL/index'
  },
  {
    text: '入门指南',
    link: '/入门指南/index'
  },
  {
    text: '流程图',
    link: '/流程图/index'
  },
  {
    text: '源代码',
    link: '/源代码/index'
  }
];
