// nav.ts generated by script,don't edit manually
export default [
  {
    text: '0.10.3',
    link: '/0.10.3/index',
  },
  {
    text: 'ChatGPT',
    link: '/ChatGPT/index',
  },
  {
    text: 'Studio',
    link: '/Studio/index',
  },
  {
    text: 'YaoDSL',
    link: '/YaoDSL/index',
  },
  {
    text: '流程图',
    link: '/流程图/index',
  },
];
