// sidebar.ts generated by script,don't edit manually
export default {
  '/': [
    {
      text: 'contributing',
      link: 'contributing',
    },
  ],
  '/Admin-App/': [
    {
      text: 'amis-yao-admin',
      link: '/Admin-App/amis-yao-admin',
    },
    {
      text: '教程',
      collapsed: true,
      items: [
        {
          text: '1项目介绍',
          link: '/Admin-App/教程/1项目介绍',
        },
        {
          text: '2项目安装',
          link: '/Admin-App/教程/2项目安装',
        },
        {
          text: '3模型管理',
          link: '/Admin-App/教程/3模型管理',
        },
        {
          text: '4数据维护',
          link: '/Admin-App/教程/4数据维护',
        },
        {
          text: '5代码生成',
          link: '/Admin-App/教程/5代码生成',
        },
        {
          text: '6页面编辑器',
          link: '/Admin-App/教程/6页面编辑器',
        },
      ],
      link: '/Admin-App/教程/',
    },
    {
      text: 'Amis',
      collapsed: true,
      items: [
        {
          text: '表单控件列表',
          link: '/Admin-App/Amis/表单控件列表',
        },
        {
          text: '表达式',
          link: '/Admin-App/Amis/表达式',
        },
        {
          text: '弹出框的两种方式',
          link: '/Admin-App/Amis/弹出框的两种方式',
        },
        {
          text: '控件字段状态的几状方法',
          link: '/Admin-App/Amis/控件字段状态的几状方法',
        },
        {
          text: '使用amis需要注意的地方',
          link: '/Admin-App/Amis/使用amis需要注意的地方',
        },
        {
          text: '事件动作中的reload',
          link: '/Admin-App/Amis/事件动作中的reload',
        },
        {
          text: '适配yao的fetcher',
          link: '/Admin-App/Amis/适配yao的fetcher',
        },
        {
          text: '自定义事件检查',
          link: '/Admin-App/Amis/自定义事件检查',
        },
        {
          text: '组件事件刷新reload',
          link: '/Admin-App/Amis/组件事件刷新reload',
        },
        {
          text: '组件查找逻辑',
          link: '/Admin-App/Amis/组件查找逻辑',
        },
        {
          text: 'amis fetcher的工作原理',
          link: '/Admin-App/Amis/amis fetcher的工作原理',
        },
        {
          text: 'amis与yao集成',
          link: '/Admin-App/Amis/amis与yao集成',
        },
        {
          text: 'amis关键字',
          link: '/Admin-App/Amis/amis关键字',
        },
        {
          text: 'dialog组件',
          link: '/Admin-App/Amis/dialog组件',
        },
        {
          text: 'font-awesome',
          link: '/Admin-App/Amis/font-awesome',
        },
        {
          text: 'InputTable的数据更新',
          link: '/Admin-App/Amis/InputTable的数据更新',
        },
        {
          text: 'js写入登录cookie',
          link: '/Admin-App/Amis/js写入登录cookie',
        },
        {
          text: 'propsTransform',
          link: '/Admin-App/Amis/propsTransform',
        },
        {
          text: 'soybean-admin路由处理',
          link: '/Admin-App/Amis/soybean-admin路由处理',
        },
        {
          text: 'Select控件联动',
          link: '/Admin-App/Amis/Select控件联动',
        },
      ],
      link: '/Admin-App/Amis/',
    },
  ],
  '/AI/': [
    {
      text: '使用postgresql保存Embedding',
      link: '/AI/使用postgresql保存Embedding',
    },
    {
      text: 'ai模型列表',
      link: '/AI/ai模型列表',
    },
    {
      text: 'ChatGPT',
      collapsed: true,
      items: [
        {
          text: '使用ChatGPT开发YAO应用',
          link: '/AI/ChatGPT/使用ChatGPT开发YAO应用',
        },
        {
          text: '使用gpt4助手创建模型定义',
          link: '/AI/ChatGPT/使用gpt4助手创建模型定义',
        },
        {
          text: 'Vscode编辑器使用插件快速开发模型',
          link: '/AI/ChatGPT/Vscode编辑器使用插件快速开发模型',
        },
        {
          text: 'Prompts',
          collapsed: true,
          items: [
            {
              text: 'ChatGPT生成模型模板',
              link: '/AI/ChatGPT/Prompts/ChatGPT生成模型模板',
            },
            {
              text: 'model_without_relations',
              link: '/AI/ChatGPT/Prompts/model_without_relations',
            },
            {
              text: 'model_with_relations',
              link: '/AI/ChatGPT/Prompts/model_with_relations',
            },
            {
              text: 'Prompt工程',
              link: '/AI/ChatGPT/Prompts/Prompt工程',
            },
          ],
          link: '/AI/ChatGPT/Prompts/',
        },
      ],
      link: '/AI/ChatGPT/',
    },
  ],
  '/Studio/': [
    {
      text: '编辑器vscode智能提示',
      link: '/Studio/编辑器vscode智能提示',
    },
    {
      text: '如何修改管理员用户密码',
      link: '/Studio/如何修改管理员用户密码',
    },
    {
      text: '自动生成table_form定义文件',
      link: '/Studio/自动生成table_form定义文件',
    },
    {
      text: 'vscode调试yao',
      link: '/Studio/vscode调试yao',
    },
    {
      text: 'yao run 命令中的特殊字符',
      link: '/Studio/yao run 命令中的特殊字符',
    },
    {
      text: 'Yao Studio介绍',
      link: '/Studio/Yao Studio介绍',
    },
    {
      text: 'Yao-admin',
      collapsed: true,
      items: [
        {
          text: 'yao-admin 根据数据库生成管理后台',
          link: '/Studio/Yao-admin/yao-admin 根据数据库生成管理后台',
        },
        {
          text: 'yao-admin 的前提条件',
          link: '/Studio/Yao-admin/yao-admin 的前提条件',
        },
      ],
      link: '/Studio/Yao-admin/',
    },
  ],
  '/UI/': [
    {
      text: 'Sui',
      collapsed: true,
      items: [
        {
          text: '使用builder创建sui页面',
          link: '/UI/Sui/使用builder创建sui页面',
        },
        {
          text: '使用sui搭建网站',
          link: '/UI/Sui/使用sui搭建网站',
        },
        {
          text: 'sui',
          link: '/UI/Sui/sui',
        },
      ],
      link: '/UI/Sui/',
    },
    {
      text: 'Xgen',
      collapsed: true,
      items: [
        {
          text: '0.10.2与0.10.3差异',
          link: '/UI/Xgen/0.10.2与0.10.3差异',
        },
        {
          text: '菜单结构',
          link: '/UI/Xgen/菜单结构',
        },
        {
          text: '系统默认的用户名',
          link: '/UI/Xgen/系统默认的用户名',
        },
        {
          text: 'Hook参数说明',
          link: '/UI/Xgen/Hook参数说明',
        },
        {
          text: 'xgen命令汇总',
          link: '/UI/Xgen/xgen命令汇总',
        },
        {
          text: 'xgen登录过程',
          link: '/UI/Xgen/xgen登录过程',
        },
        {
          text: 'xgen远程onChange事件',
          link: '/UI/Xgen/xgen远程onChange事件',
        },
        {
          text: 'Xgen多语言支持',
          link: '/UI/Xgen/Xgen多语言支持',
        },
        {
          text: 'Form',
          collapsed: true,
          items: [
            {
              text: 'AI智能表单',
              link: '/UI/Xgen/Form/AI智能表单',
            },
            {
              text: 'Form使用技巧',
              link: '/UI/Xgen/Form/Form使用技巧',
            },
            {
              text: 'Form单据参考创建',
              link: '/UI/Xgen/Form/Form单据参考创建',
            },
            {
              text: 'Form里嵌套List',
              link: '/UI/Xgen/Form/Form里嵌套List',
            },
            {
              text: 'Form里嵌套Table',
              link: '/UI/Xgen/Form/Form里嵌套Table',
            },
          ],
          link: '/UI/Xgen/Form/',
        },
        {
          text: 'Neo',
          collapsed: true,
          items: [
            {
              text: 'neo嵌入业务指令',
              link: '/UI/Xgen/Neo/neo嵌入业务指令',
            },
          ],
          link: '/UI/Xgen/Neo/',
        },
        {
          text: 'Table',
          collapsed: true,
          items: [
            {
              text: 'TableA跳转到FormB',
              link: '/UI/Xgen/Table/TableA跳转到FormB',
            },
            {
              text: 'Table_Form禁用Action',
              link: '/UI/Xgen/Table/Table_Form禁用Action',
            },
            {
              text: 'Table上使用Tab',
              link: '/UI/Xgen/Table/Table上使用Tab',
            },
            {
              text: 'Table中设置字段只读',
              link: '/UI/Xgen/Table/Table中设置字段只读',
            },
            {
              text: 'Table使用技巧',
              link: '/UI/Xgen/Table/Table使用技巧',
            },
            {
              text: 'Table增加查看，编辑，删除按钮',
              link: '/UI/Xgen/Table/Table增加查看，编辑，删除按钮',
            },
            {
              text: 'Table搜索默认值',
              link: '/UI/Xgen/Table/Table搜索默认值',
            },
            {
              text: 'Table最小化配置',
              link: '/UI/Xgen/Table/Table最小化配置',
            },
            {
              text: 'Table界面上增加创建按钮',
              link: '/UI/Xgen/Table/Table界面上增加创建按钮',
            },
          ],
          link: '/UI/Xgen/Table/',
        },
        {
          text: 'Xgen控件',
          collapsed: true,
          items: [
            {
              text: '菜单配置',
              link: '/UI/Xgen/Xgen控件/菜单配置',
            },
            {
              text: '禁用编辑控件',
              link: '/UI/Xgen/Xgen控件/禁用编辑控件',
            },
            {
              text: '控件onSelect回调',
              link: '/UI/Xgen/Xgen控件/控件onSelect回调',
            },
            {
              text: '设置控件的必输属性',
              link: '/UI/Xgen/Xgen控件/设置控件的必输属性',
            },
            {
              text: '使用Hook转换日期控件的值',
              link: '/UI/Xgen/Xgen控件/使用Hook转换日期控件的值',
            },
            {
              text: '视频上传',
              link: '/UI/Xgen/Xgen控件/视频上传',
            },
            {
              text: '图片控件',
              link: '/UI/Xgen/Xgen控件/图片控件',
            },
            {
              text: '文件上传UploadFile',
              link: '/UI/Xgen/Xgen控件/文件上传UploadFile',
            },
            {
              text: '远程select控件',
              link: '/UI/Xgen/Xgen控件/远程select控件',
            },
            {
              text: 'Switch控件',
              link: '/UI/Xgen/Xgen控件/Switch控件',
            },
            {
              text: 'Upload在List下视频样式错乱',
              link: '/UI/Xgen/Xgen控件/Upload在List下视频样式错乱',
            },
            {
              text: 'Xgen登录界面邮件电话校验规则',
              link: '/UI/Xgen/Xgen控件/Xgen登录界面邮件电话校验规则',
            },
            {
              text: 'Xgen自定义远程控件',
              link: '/UI/Xgen/Xgen控件/Xgen自定义远程控件',
            },
            {
              text: 'RichText富文本控件',
              collapsed: true,
              items: [
                {
                  text: '使用富文本控件',
                  link: '/UI/Xgen/Xgen控件/RichText富文本控件/使用富文本控件',
                },
              ],
              link: '/UI/Xgen/Xgen控件/RichText富文本控件/',
            },
          ],
          link: '/UI/Xgen/Xgen控件/',
        },
      ],
      link: '/UI/Xgen/',
    },
  ],
  '/YaoDSL/': [
    {
      text: '使用compute',
      link: '/YaoDSL/使用compute',
    },
    {
      text: '处理器',
      collapsed: true,
      items: [
        {
          text: '处理器列表',
          link: '/YaoDSL/处理器/处理器列表',
        },
        {
          text: 'Array转树形结构',
          link: '/YaoDSL/处理器/Array转树形结构',
        },
      ],
      link: '/YaoDSL/处理器/',
    },
    {
      text: 'AIGC',
      collapsed: true,
      items: [
        {
          text: 'aigc处理器',
          link: '/YaoDSL/AIGC/aigc处理器',
        },
        {
          text: 'chatgpt模型中角色的作用',
          link: '/YaoDSL/AIGC/chatgpt模型中角色的作用',
        },
        {
          text: 'neo_api接口',
          link: '/YaoDSL/AIGC/neo_api接口',
        },
        {
          text: 'neo命令',
          link: '/YaoDSL/AIGC/neo命令',
        },
        {
          text: 'neo聊天助手',
          link: '/YaoDSL/AIGC/neo聊天助手',
        },
        {
          text: 'openai处理器',
          link: '/YaoDSL/AIGC/openai处理器',
        },
        {
          text: 'sse函数',
          link: '/YaoDSL/AIGC/sse函数',
        },
      ],
      link: '/YaoDSL/AIGC/',
    },
    {
      text: 'API',
      collapsed: true,
      items: [
        {
          text: '超级用户权限',
          link: '/YaoDSL/API/超级用户权限',
        },
        {
          text: '配置Redis保存会话',
          link: '/YaoDSL/API/配置Redis保存会话',
        },
        {
          text: '刷新token',
          link: '/YaoDSL/API/刷新token',
        },
        {
          text: '文件上传下载接口',
          link: '/YaoDSL/API/文件上传下载接口',
        },
        {
          text: '自定义用户登陆login api',
          link: '/YaoDSL/API/自定义用户登陆login api',
        },
        {
          text: 'API Guard',
          link: '/YaoDSL/API/API Guard',
        },
        {
          text: 'API会话session保持',
          link: '/YaoDSL/API/API会话session保持',
        },
        {
          text: 'API引用上下文变量',
          link: '/YaoDSL/API/API引用上下文变量',
        },
        {
          text: 'API预定义变量',
          link: '/YaoDSL/API/API预定义变量',
        },
        {
          text: 'service接口',
          link: '/YaoDSL/API/service接口',
        },
        {
          text: 'stream api接口',
          link: '/YaoDSL/API/stream api接口',
        },
        {
          text: 'stream http客户端请求',
          link: '/YaoDSL/API/stream http客户端请求',
        },
      ],
      link: '/YaoDSL/API/',
    },
    {
      text: 'Model',
      collapsed: true,
      items: [
        {
          text: '定义一个业务模型',
          link: '/YaoDSL/Model/定义一个业务模型',
        },
        {
          text: '定义多对一关联关系',
          link: '/YaoDSL/Model/定义多对一关联关系',
        },
        {
          text: '模型处理器列表',
          link: '/YaoDSL/Model/模型处理器列表',
        },
        {
          text: '模型字段校验',
          link: '/YaoDSL/Model/模型字段校验',
        },
        {
          text: '模型字段类型',
          link: '/YaoDSL/Model/模型字段类型',
        },
        {
          text: '字段aes加密解密',
          link: '/YaoDSL/Model/字段aes加密解密',
        },
        {
          text: 'sqlite与mysql的差异',
          link: '/YaoDSL/Model/sqlite与mysql的差异',
        },
      ],
      link: '/YaoDSL/Model/',
    },
    {
      text: 'Plugin',
      collapsed: true,
      items: [
        {
          text: '飞书自定义登录',
          link: '/YaoDSL/Plugin/飞书自定义登录',
        },
        {
          text: 'golang grpc 插件模板',
          link: '/YaoDSL/Plugin/golang grpc 插件模板',
        },
        {
          text: 'grpc插件',
          link: '/YaoDSL/Plugin/grpc插件',
        },
      ],
      link: '/YaoDSL/Plugin/',
    },
    {
      text: 'Query',
      collapsed: true,
      items: [
        {
          text: '在url中使用QueryParam',
          link: '/YaoDSL/Query/在url中使用QueryParam',
        },
        {
          text: 'Flow Query绑定变量',
          link: '/YaoDSL/Query/Flow Query绑定变量',
        },
        {
          text: 'Flow处理器与JSAPI区别',
          link: '/YaoDSL/Query/Flow处理器与JSAPI区别',
        },
        {
          text: 'JSAPI',
          link: '/YaoDSL/Query/JSAPI',
        },
        {
          text: 'QueryDsl',
          link: '/YaoDSL/Query/QueryDsl',
        },
        {
          text: 'QueryParam与QueryDSL',
          link: '/YaoDSL/Query/QueryParam与QueryDSL',
        },
        {
          text: 'QueryParam语法',
          link: '/YaoDSL/Query/QueryParam语法',
        },
      ],
      link: '/YaoDSL/Query/',
    },
    {
      text: 'Store',
      collapsed: true,
      items: [
        {
          text: 'Mongo配置',
          link: '/YaoDSL/Store/Mongo配置',
        },
      ],
      link: '/YaoDSL/Store/',
    },
    {
      text: 'Task',
      collapsed: true,
      items: [
        {
          text: '使用任务',
          link: '/YaoDSL/Task/使用任务',
        },
      ],
      link: '/YaoDSL/Task/',
    },
    {
      text: 'v8go',
      collapsed: true,
      items: [
        {
          text: '后台异常执行作业',
          link: '/YaoDSL/v8go/后台异常执行作业',
        },
        {
          text: '小心字节处理',
          link: '/YaoDSL/v8go/小心字节处理',
        },
        {
          text: '在js脚本中抛出异常',
          link: '/YaoDSL/v8go/在js脚本中抛出异常',
        },
        {
          text: '在yao中使用外部库',
          link: '/YaoDSL/v8go/在yao中使用外部库',
        },
        {
          text: 'Promise',
          link: '/YaoDSL/v8go/Promise',
        },
      ],
      link: '/YaoDSL/v8go/',
    },
    {
      text: 'Widget',
      collapsed: true,
      items: [
        {
          text: '自定义Widget',
          link: '/YaoDSL/Widget/自定义Widget',
        },
        {
          text: '自定义Widget升级版',
          link: '/YaoDSL/Widget/自定义Widget升级版',
        },
      ],
      link: '/YaoDSL/Widget/',
    },
  ],
  '/入门指南/': [
    {
      text: 'readme',
      link: '/入门指南/readme',
    },
    {
      text: 'Yao学习路线图',
      link: '/入门指南/Yao学习路线图',
    },
    {
      text: 'Yao简单介绍',
      link: '/入门指南/Yao简单介绍',
    },
    {
      text: '进阶系列',
      collapsed: true,
      items: [
        {
          text: '后台执行',
          link: '/入门指南/进阶系列/后台执行',
        },
        {
          text: '使用会话保存信息',
          link: '/入门指南/进阶系列/使用会话保存信息',
        },
        {
          text: 'yao源代码安装',
          link: '/入门指南/进阶系列/yao源代码安装',
        },
      ],
      link: '/入门指南/进阶系列/',
    },
    {
      text: '上手系列',
      collapsed: true,
      items: [
        {
          text: '1 Yao下载与安装',
          link: '/入门指南/上手系列/1 Yao下载与安装',
        },
        {
          text: '2 创建第一个Yao应用',
          link: '/入门指南/上手系列/2 创建第一个Yao应用',
        },
        {
          text: '3 增加模型定义',
          link: '/入门指南/上手系列/3 增加模型定义',
        },
        {
          text: '4 生成数据库表',
          link: '/入门指南/上手系列/4 生成数据库表',
        },
        {
          text: '5 配置表格',
          link: '/入门指南/上手系列/5 配置表格',
        },
        {
          text: '6 配置表单',
          link: '/入门指南/上手系列/6 配置表单',
        },
        {
          text: '7 配置外部API',
          link: '/入门指南/上手系列/7 配置外部API',
        },
        {
          text: '8 处理器',
          link: '/入门指南/上手系列/8 处理器',
        },
        {
          text: '9 数据增删改查',
          link: '/入门指南/上手系列/9 数据增删改查',
        },
      ],
      link: '/入门指南/上手系列/',
    },
  ],
  '/流程图/': [
    {
      text: '查询参数QueryParam',
      link: '/流程图/查询参数QueryParam',
    },
    {
      text: '任务Task处理',
      link: '/流程图/任务Task处理',
    },
    {
      text: '数据库schema',
      link: '/流程图/数据库schema',
    },
    {
      text: '数据库xun架构',
      link: '/流程图/数据库xun架构',
    },
    {
      text: '数据库更新流程',
      link: '/流程图/数据库更新流程',
    },
    {
      text: '数据库读取流程',
      link: '/流程图/数据库读取流程',
    },
    {
      text: '用户登录流程会话',
      link: '/流程图/用户登录流程会话',
    },
    {
      text: '自定义widget',
      link: '/流程图/自定义widget',
    },
    {
      text: 'api请求过程',
      link: '/流程图/api请求过程',
    },
    {
      text: 'yao migrate',
      link: '/流程图/yao migrate',
    },
    {
      text: 'Yao 架构概览',
      link: '/流程图/Yao 架构概览',
    },
  ],
  '/源代码/': [
    {
      text: 'Github Commit List',
      link: '/源代码/Github Commit List',
    },
    {
      text: '源码编译',
      collapsed: true,
      items: [
        {
          text: '0.10.3-pre To 0.10.3-dev',
          link: '/源代码/源码编译/0.10.3-pre To 0.10.3-dev',
        },
        {
          text: '编译yao源代码',
          link: '/源代码/源码编译/编译yao源代码',
        },
        {
          text: 'windows版本适配',
          collapsed: true,
          items: [
            {
              text: '编译yao windows修改版本',
              link: '/源代码/源码编译/windows版本适配/编译yao windows修改版本',
            },
            {
              text: 'windows pack功能适配',
              link: '/源代码/源码编译/windows版本适配/windows pack功能适配',
            },
          ],
          link: '/源代码/源码编译/windows版本适配/',
        },
      ],
      link: '/源代码/源码编译/',
    },
    {
      text: 'Gou',
      collapsed: true,
      items: [
        {
          text: '加密处理器调用错误',
          link: '/源代码/Gou/加密处理器调用错误',
        },
        {
          text: '两个HasMany问题',
          link: '/源代码/Gou/两个HasMany问题',
        },
        {
          text: '数据库Schema默认值转换异常',
          link: '/源代码/Gou/数据库Schema默认值转换异常',
        },
        {
          text: 'jsapi中的undefined转换',
          link: '/源代码/Gou/jsapi中的undefined转换',
        },
        {
          text: 'Null值转换成Int类型值时panic',
          link: '/源代码/Gou/Null值转换成Int类型值时panic',
        },
      ],
      link: '/源代码/Gou/',
    },
    {
      text: 'Kun',
      collapsed: true,
      items: [
        {
          text: 'console_log无法输出正确格式',
          link: '/源代码/Kun/console_log无法输出正确格式',
        },
      ],
      link: '/源代码/Kun/',
    },
    {
      text: 'Xgen',
      collapsed: true,
      items: [
        {
          text: 'xgen List控件保存数据时数据被清空',
          link: '/源代码/Xgen/xgen List控件保存数据时数据被清空',
        },
        {
          text: 'xgen remoteSearch',
          link: '/源代码/Xgen/xgen remoteSearch',
        },
        {
          text: 'xgen 批量上传功能',
          link: '/源代码/Xgen/xgen 批量上传功能',
        },
      ],
      link: '/源代码/Xgen/',
    },
    {
      text: 'Xun',
      collapsed: true,
      items: [
        {
          text: '数据库连接配置',
          link: '/源代码/Xun/数据库连接配置',
        },
        {
          text: 'Mysql数据库事务',
          link: '/源代码/Xun/Mysql数据库事务',
        },
        {
          text: 'PG数据库增加自定义类型',
          link: '/源代码/Xun/PG数据库增加自定义类型',
        },
        {
          text: 'sqlite数据库bug',
          link: '/源代码/Xun/sqlite数据库bug',
        },
      ],
      link: '/源代码/Xun/',
    },
    {
      text: 'Yao',
      collapsed: true,
      items: [
        {
          text: '处理器yao.component.selectoptions修正',
          link: '/源代码/Yao/处理器yao.component.selectoptions修正',
        },
        {
          text: 'Compute 处理器无法处理关联表',
          link: '/源代码/Yao/Compute 处理器无法处理关联表',
        },
        {
          text: 'yao 应用打包功能pack',
          link: '/源代码/Yao/yao 应用打包功能pack',
        },
      ],
      link: '/源代码/Yao/',
    },
  ],
};
