// sidebar.ts generated by script,don't edit manually
export default
{
  '/': [
    {
      text: 'contributing',
      link: 'contributing',
    },
    {
      text: 'readme',
      link: 'readme',
    },
  ],
  '/0.10.3/': [
    {
      text: '0.10.2与0.10.3差异',
      link: '/0.10.3/0.10.2与0.10.3差异',
    },
    {
      text: 'Hook参数说明',
      link: '/0.10.3/Hook参数说明',
    },
    {
      text: '后台执行',
      link: '/0.10.3/后台执行',
    },
    {
      text: '系统默认的用户名',
      link: '/0.10.3/系统默认的用户名',
    },
    {
      text: '编译yao源代码',
      link: '/0.10.3/编译yao源代码',
    },
    {
      text: '编辑器vscode智能提示',
      link: '/0.10.3/编辑器vscode智能提示',
    },
    {
      text: '菜单结构',
      link: '/0.10.3/菜单结构',
    },
    {
      text: 'Bugs',
      collapsed: true,
      items: [
        {
          text: 'console_log无法输出正确格式',
          link: '/0.10.3/Bugs/console_log无法输出正确格式',
        },
        {
          text: 'Compute 处理器无法处理关联表',
          link: '/0.10.3/Bugs/Compute 处理器无法处理关联表',
        },
        {
          text: 'sqlite数据库bug',
          link: '/0.10.3/Bugs/sqlite数据库bug',
        },
        {
          text: 'xgen List控件保存数据时数据被清空',
          link: '/0.10.3/Bugs/xgen List控件保存数据时数据被清空',
        },
        {
          text: 'xgen remoteSearch',
          link: '/0.10.3/Bugs/xgen remoteSearch',
        },
        {
          text: 'xgen 批量上传功能',
          link: '/0.10.3/Bugs/xgen 批量上传功能',
        },
        {
          text: '加密处理器调用错误',
          link: '/0.10.3/Bugs/加密处理器调用错误',
        },
        {
          text: '处理器yao.component.selectoptions修正',
          link: '/0.10.3/Bugs/处理器yao.component.selectoptions修正',
        },
      ],
      link: '/0.10.3/Bugs/',
    },
    {
      text: 'ChatGPT',
      collapsed: true,
      items: [
        {
          text: '使用ChatGPT开发YAO应用',
          link: '/0.10.3/ChatGPT/使用ChatGPT开发YAO应用',
        },
        {
          text: 'Prompts',
          collapsed: true,
          items: [
            {
              text: 'ChatGPT生成模型模板',
              link: '/0.10.3/ChatGPT/Prompts/ChatGPT生成模型模板',
            },
            {
              text: 'model_with_relations',
              link: '/0.10.3/ChatGPT/Prompts/model_with_relations',
            },
            {
              text: 'model_without_relations',
              link: '/0.10.3/ChatGPT/Prompts/model_without_relations',
            },
          ],
          link: '/0.10.3/ChatGPT/Prompts/',
        },
      ],
      link: '/0.10.3/ChatGPT/',
    },
    {
      text: 'Form',
      collapsed: true,
      items: [
        {
          text: 'Form使用技巧',
          link: '/0.10.3/Form/Form使用技巧',
        },
        {
          text: '在Form里使用子表',
          link: '/0.10.3/Form/在Form里使用子表',
        },
      ],
      link: '/0.10.3/Form/',
    },
    {
      text: 'Studio',
      collapsed: true,
      items: [
        {
          text: '如何修改用户密码',
          link: '/0.10.3/Studio/如何修改用户密码',
        },
        {
          text: '自动生成table_form定义文件',
          link: '/0.10.3/Studio/自动生成table_form定义文件',
        },
      ],
      link: '/0.10.3/Studio/',
    },
    {
      text: 'Table',
      collapsed: true,
      items: [
        {
          text: 'TableA跳转到FormB',
          link: '/0.10.3/Table/TableA跳转到FormB',
        },
        {
          text: 'Table使用技巧',
          link: '/0.10.3/Table/Table使用技巧',
        },
        {
          text: 'Table最小化配置',
          link: '/0.10.3/Table/Table最小化配置',
        },
        {
          text: '在table中设置字段只读',
          link: '/0.10.3/Table/在table中设置字段只读',
        },
        {
          text: '在table界面上增加创建按钮',
          link: '/0.10.3/Table/在table界面上增加创建按钮',
        },
        {
          text: '增加查看，编辑，删除按钮',
          link: '/0.10.3/Table/增加查看，编辑，删除按钮',
        },
        {
          text: '搜索默认值',
          link: '/0.10.3/Table/搜索默认值',
        },
      ],
      link: '/0.10.3/Table/',
    },
    {
      text: 'Xgen控件',
      collapsed: true,
      items: [
        {
          text: 'Switch控件',
          link: '/0.10.3/Xgen控件/Switch控件',
        },
        {
          text: '使用Hook转换日期控件的值',
          link: '/0.10.3/Xgen控件/使用Hook转换日期控件的值',
        },
        {
          text: '图片控件',
          link: '/0.10.3/Xgen控件/图片控件',
        },
        {
          text: '控件onSelect回调',
          link: '/0.10.3/Xgen控件/控件onSelect回调',
        },
        {
          text: '文件上传',
          link: '/0.10.3/Xgen控件/文件上传',
        },
        {
          text: '根据条件禁用`Table_Form Action`按钮',
          link: '/0.10.3/Xgen控件/根据条件禁用`Table_Form Action`按钮',
        },
        {
          text: '禁用编辑控件',
          link: '/0.10.3/Xgen控件/禁用编辑控件',
        },
        {
          text: '设置控件的必输属性',
          link: '/0.10.3/Xgen控件/设置控件的必输属性',
        },
        {
          text: '远程select控件',
          link: '/0.10.3/Xgen控件/远程select控件',
        },
        {
          text: '富文本控件',
          collapsed: true,
          items: [
            {
              text: '使用富文本控件',
              link: '/0.10.3/Xgen控件/富文本控件/使用富文本控件',
            },
          ],
          link: '/0.10.3/Xgen控件/富文本控件/',
        },
      ],
      link: '/0.10.3/Xgen控件/',
    },
    {
      text: '插件',
      collapsed: true,
      items: [
        {
          text: 'golang grpc 插件模板',
          link: '/0.10.3/插件/golang grpc 插件模板',
        },
      ],
      link: '/0.10.3/插件/',
    },
    {
      text: '数据库',
      collapsed: true,
      items: [
        {
          text: 'sqlite与mysql的差异',
          link: '/0.10.3/数据库/sqlite与mysql的差异',
        },
        {
          text: '模型多对一',
          collapsed: true,
          items: [
            {
              text: '一对一，多对一关联关系定义',
              link: '/0.10.3/数据库/模型多对一/一对一，多对一关联关系定义',
            },
          ],
          link: '/0.10.3/数据库/模型多对一/',
        },
      ],
      link: '/0.10.3/数据库/',
    },
  ],
  '/流程图/': [
    {
      text: 'api请求过程',
      link: '/流程图/api请求过程',
    },
    {
      text: 'yao_migrate',
      link: '/流程图/yao_migrate',
    },
    {
      text: '任务Task处理',
      link: '/流程图/任务Task处理',
    },
    {
      text: '数据库schema',
      link: '/流程图/数据库schema',
    },
    {
      text: '数据库xun架构',
      link: '/流程图/数据库xun架构',
    },
    {
      text: '数据库更新流程',
      link: '/流程图/数据库更新流程',
    },
    {
      text: '数据库读取流程',
      link: '/流程图/数据库读取流程',
    },
    {
      text: '查询参数QueryParam',
      link: '/流程图/查询参数QueryParam',
    },
    {
      text: '用户登录流程会话',
      link: '/流程图/用户登录流程会话',
    },
    {
      text: '自定义widget',
      link: '/流程图/自定义widget',
    },
  ],
}
