// sidebar.ts generated by script,don't edit manually
export default {
  '/': [
    {
      text: 'contributing',
      link: 'contributing',
    },
  ],
  '/0.10.3/': [
    {
      text: '0.10.2与0.10.3差异',
      link: '/0.10.3/0.10.2与0.10.3差异',
    },
    {
      text: 'Hook参数说明',
      link: '/0.10.3/Hook参数说明',
    },
    {
      text: '后台执行',
      link: '/0.10.3/后台执行',
    },
    {
      text: '系统默认的用户名',
      link: '/0.10.3/系统默认的用户名',
    },
    {
      text: '菜单结构',
      link: '/0.10.3/菜单结构',
    },
    {
      text: 'Form',
      collapsed: true,
      items: [
        {
          text: 'Form使用技巧',
          link: '/0.10.3/Form/Form使用技巧',
        },
        {
          text: '单据参考创建',
          link: '/0.10.3/Form/单据参考创建',
        },
        {
          text: '在Form里使用子表',
          link: '/0.10.3/Form/在Form里使用子表',
        },
      ],
      link: '/0.10.3/Form/',
    },
    {
      text: 'Table',
      collapsed: true,
      items: [
        {
          text: 'TableA跳转到FormB',
          link: '/0.10.3/Table/TableA跳转到FormB',
        },
        {
          text: 'Table使用技巧',
          link: '/0.10.3/Table/Table使用技巧',
        },
        {
          text: 'Table最小化配置',
          link: '/0.10.3/Table/Table最小化配置',
        },
        {
          text: '在table中设置字段只读',
          link: '/0.10.3/Table/在table中设置字段只读',
        },
        {
          text: '在table界面上增加创建按钮',
          link: '/0.10.3/Table/在table界面上增加创建按钮',
        },
        {
          text: '增加查看，编辑，删除按钮',
          link: '/0.10.3/Table/增加查看，编辑，删除按钮',
        },
        {
          text: '搜索默认值',
          link: '/0.10.3/Table/搜索默认值',
        },
      ],
      link: '/0.10.3/Table/',
    },
    {
      text: 'Xgen控件',
      collapsed: true,
      items: [
        {
          text: 'Switch控件',
          link: '/0.10.3/Xgen控件/Switch控件',
        },
        {
          text: 'Xgen多语言支持',
          link: '/0.10.3/Xgen控件/Xgen多语言支持',
        },
        {
          text: '使用Hook转换日期控件的值',
          link: '/0.10.3/Xgen控件/使用Hook转换日期控件的值',
        },
        {
          text: '图片控件',
          link: '/0.10.3/Xgen控件/图片控件',
        },
        {
          text: '控件onSelect回调',
          link: '/0.10.3/Xgen控件/控件onSelect回调',
        },
        {
          text: '文件上传',
          link: '/0.10.3/Xgen控件/文件上传',
        },
        {
          text: '根据条件禁用`Table_Form Action`按钮',
          link: '/0.10.3/Xgen控件/根据条件禁用`Table_Form Action`按钮',
        },
        {
          text: '禁用编辑控件',
          link: '/0.10.3/Xgen控件/禁用编辑控件',
        },
        {
          text: '菜单配置',
          link: '/0.10.3/Xgen控件/菜单配置',
        },
        {
          text: '设置控件的必输属性',
          link: '/0.10.3/Xgen控件/设置控件的必输属性',
        },
        {
          text: '远程select控件',
          link: '/0.10.3/Xgen控件/远程select控件',
        },
        {
          text: '富文本控件',
          collapsed: true,
          items: [
            {
              text: '使用富文本控件',
              link: '/0.10.3/Xgen控件/富文本控件/使用富文本控件',
            },
          ],
          link: '/0.10.3/Xgen控件/富文本控件/',
        },
        {
          text: '自定义',
          collapsed: true,
          items: [
            {
              text: '表格跳转表单携带数据',
              link: '/0.10.3/Xgen控件/自定义/表格跳转表单携带数据',
            },
          ],
          link: '/0.10.3/Xgen控件/自定义/',
        },
      ],
      link: '/0.10.3/Xgen控件/',
    },
  ],
  '/ChatGPT/': [
    {
      text: 'Vscode编辑器使用插件快速开发模型',
      link: '/ChatGPT/Vscode编辑器使用插件快速开发模型',
    },
    {
      text: '使用ChatGPT开发YAO应用',
      link: '/ChatGPT/使用ChatGPT开发YAO应用',
    },
    {
      text: 'Prompts',
      collapsed: true,
      items: [
        {
          text: 'ChatGPT生成模型模板',
          link: '/ChatGPT/Prompts/ChatGPT生成模型模板',
        },
        {
          text: 'model_with_relations',
          link: '/ChatGPT/Prompts/model_with_relations',
        },
        {
          text: 'model_without_relations',
          link: '/ChatGPT/Prompts/model_without_relations',
        },
      ],
      link: '/ChatGPT/Prompts/',
    },
  ],
  '/Studio/': [
    {
      text: 'vscode调试yao',
      link: '/Studio/vscode调试yao',
    },
    {
      text: 'Yao Studio介绍',
      link: '/Studio/Yao Studio介绍',
    },
    {
      text: '如何修改管理员用户密码',
      link: '/Studio/如何修改管理员用户密码',
    },
    {
      text: '编辑器vscode智能提示',
      link: '/Studio/编辑器vscode智能提示',
    },
    {
      text: '自动生成table_form定义文件',
      link: '/Studio/自动生成table_form定义文件',
    },
  ],
  '/YaoDSL/': [
    {
      text: 'API',
      collapsed: true,
      items: [
        {
          text: 'API Guard',
          link: '/YaoDSL/API/API Guard',
        },
        {
          text: 'API预定义变量',
          link: '/YaoDSL/API/API预定义变量',
        },
        {
          text: '在api中使用变量引用上下文变量',
          link: '/YaoDSL/API/在api中使用变量引用上下文变量',
        },
        {
          text: '服务器端会话session保持',
          link: '/YaoDSL/API/服务器端会话session保持',
        },
        {
          text: '自定义用户登陆API',
          link: '/YaoDSL/API/自定义用户登陆API',
        },
      ],
      link: '/YaoDSL/API/',
    },
    {
      text: 'Model',
      collapsed: true,
      items: [
        {
          text: 'sqlite与mysql的差异',
          link: '/YaoDSL/Model/sqlite与mysql的差异',
        },
        {
          text: '模型多对一',
          collapsed: true,
          items: [
            {
              text: '一对一，多对一关联关系定义',
              link: '/YaoDSL/Model/模型多对一/一对一，多对一关联关系定义',
            },
          ],
          link: '/YaoDSL/Model/模型多对一/',
        },
      ],
      link: '/YaoDSL/Model/',
    },
    {
      text: 'Plugin',
      collapsed: true,
      items: [
        {
          text: 'golang grpc 插件模板',
          link: '/YaoDSL/Plugin/golang grpc 插件模板',
        },
      ],
      link: '/YaoDSL/Plugin/',
    },
    {
      text: 'Query',
      collapsed: true,
      items: [
        {
          text: 'Flow中Query使用前缀绑定变量',
          link: '/YaoDSL/Query/Flow中Query使用前缀绑定变量',
        },
        {
          text: '在JsAPI中使用QueryDsl',
          link: '/YaoDSL/Query/在JsAPI中使用QueryDsl',
        },
        {
          text: '在url请求中使用查询语法QueryParam',
          link: '/YaoDSL/Query/在url请求中使用查询语法QueryParam',
        },
        {
          text: '数据查询使用SQL.STMT需要注意的问题',
          link: '/YaoDSL/Query/数据查询使用SQL.STMT需要注意的问题',
        },
      ],
      link: '/YaoDSL/Query/',
    },
  ],
  '/入门指南/': [
    {
      text: 'readme',
      link: '/入门指南/readme',
    },
    {
      text: 'Yao学习路线图',
      link: '/入门指南/Yao学习路线图',
    },
  ],
  '/流程图/': [
    {
      text: 'api请求过程',
      link: '/流程图/api请求过程',
    },
    {
      text: 'yao_migrate',
      link: '/流程图/yao_migrate',
    },
    {
      text: '任务Task处理',
      link: '/流程图/任务Task处理',
    },
    {
      text: '数据库schema',
      link: '/流程图/数据库schema',
    },
    {
      text: '数据库xun架构',
      link: '/流程图/数据库xun架构',
    },
    {
      text: '数据库更新流程',
      link: '/流程图/数据库更新流程',
    },
    {
      text: '数据库读取流程',
      link: '/流程图/数据库读取流程',
    },
    {
      text: '查询参数QueryParam',
      link: '/流程图/查询参数QueryParam',
    },
    {
      text: '用户登录流程会话',
      link: '/流程图/用户登录流程会话',
    },
    {
      text: '自定义widget',
      link: '/流程图/自定义widget',
    },
  ],
  '/源代码/': [
    {
      text: '0.10.3-pre To 0.10.3-dev',
      link: '/源代码/0.10.3-pre To 0.10.3-dev',
    },
    {
      text: 'Github Commit List',
      link: '/源代码/Github Commit List',
    },
    {
      text: '编译yao源代码',
      link: '/源代码/编译yao源代码',
    },
    {
      text: 'Gou',
      collapsed: true,
      items: [
        {
          text: 'Null值转换成Int类型值时panic',
          link: '/源代码/Gou/Null值转换成Int类型值时panic',
        },
        {
          text: '加密处理器调用错误',
          link: '/源代码/Gou/加密处理器调用错误',
        },
        {
          text: '数据库Schema默认值转换异常',
          link: '/源代码/Gou/数据库Schema默认值转换异常',
        },
      ],
      link: '/源代码/Gou/',
    },
    {
      text: 'Kun',
      collapsed: true,
      items: [
        {
          text: 'console_log无法输出正确格式',
          link: '/源代码/Kun/console_log无法输出正确格式',
        },
      ],
      link: '/源代码/Kun/',
    },
    {
      text: 'Xgen',
      collapsed: true,
      items: [
        {
          text: 'xgen List控件保存数据时数据被清空',
          link: '/源代码/Xgen/xgen List控件保存数据时数据被清空',
        },
        {
          text: 'xgen remoteSearch',
          link: '/源代码/Xgen/xgen remoteSearch',
        },
        {
          text: 'xgen 批量上传功能',
          link: '/源代码/Xgen/xgen 批量上传功能',
        },
      ],
      link: '/源代码/Xgen/',
    },
    {
      text: 'Xun',
      collapsed: true,
      items: [
        {
          text: 'sqlite数据库bug',
          link: '/源代码/Xun/sqlite数据库bug',
        },
      ],
      link: '/源代码/Xun/',
    },
    {
      text: 'Yao',
      collapsed: true,
      items: [
        {
          text: 'Compute 处理器无法处理关联表',
          link: '/源代码/Yao/Compute 处理器无法处理关联表',
        },
        {
          text: '处理器yao.component.selectoptions修正',
          link: '/源代码/Yao/处理器yao.component.selectoptions修正',
        },
      ],
      link: '/源代码/Yao/',
    },
  ],
};
